<div class="thrv_wrapper thrv_icon tcb-icon-display tve_evt_manager_listen tve_et_click tve_ea_thrive_leads_form_close" data-css="tve-u-15de6c6b78a" data-tcb-events="__TCB_EVENT_[{&quot;a&quot;:&quot;thrive_leads_form_close&quot;,&quot;t&quot;:&quot;click&quot;}]_TNEVE_BCT__" style=""><svg class="tcb-icon" viewBox="0 0 30 32" data-name="closeclose">
<title>close</title>
<path d="M0.655 2.801l1.257-1.257 27.655 27.655-1.257 1.257-27.655-27.655z"></path>
<path d="M28.31 1.543l1.257 1.257-27.655 27.655-1.257-1.257 27.655-27.655z"></path>
</svg></div><div class="thrv_wrapper thrv-page-section" style="" data-css="tve-u-15de66de3eb">
<div class="tve-page-section-out" data-css="tve-u-15de6be0e3a" data-clip-id="21e023dcf9758"><svg width="0" height="0" class="tve-decoration-svg"><defs><clipPath id="clip-bottom-21e023dcf9758" class="decoration-clip clip-path-bottom" clipPathUnits="objectBoundingBox" data-screen="" decoration-type="pointer" clip-path="url(#clip-top-21e023dcf9758)"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-top-21e023dcf9758" class="decoration-clip clip-path-top" clipPathUnits="objectBoundingBox" data-screen="" decoration-type="none"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath></defs></svg></div>
<div class="tve-page-section-in tve_empty_dropzone" data-css="tve-u-15de685fcae"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" style="" data-css="tve-u-15de6ae1fd1">
<div class="tve-content-box-background" data-css="tve-u-15de6ae0405" data-clip-id="876b4912f7f93"><svg width="0" height="0" class="tve-decoration-svg"><defs><clipPath id="clip-bottom-876b4912f7f93" class="decoration-clip clip-path-bottom" clipPathUnits="objectBoundingBox" data-screen="" decoration-type="pointer" pointer-width="3" pointer-height="5" style="" data-inverted="false"><polygon points="0 0, 0 0.95, 0.485 0.95, 0.5 1, 0.515 0.95, 1 0.95, 1 0"></polygon></clipPath><clipPath id="clip-mobile-bottom-876b4912f7f93" class="decoration-clip clip-path-mobile-bottom" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="pointer" pointer-width="7.000000000000001" pointer-height="3" style="" data-inverted="false"><polygon points="0 0, 0 0.97, 0.46499999999999997 0.97, 0.5 1, 0.5349999999999999 0.97, 1 0.97, 1 0"></polygon></clipPath><clipPath id="clip-tablet-bottom-876b4912f7f93" class="decoration-clip clip-path-tablet-bottom" clipPathUnits="objectBoundingBox" data-screen="tablet-" decoration-type="pointer" pointer-width="3" pointer-height="5" style="" data-inverted="false"><polygon points="0 0, 0 0.95, 0.485 0.95, 0.5 1, 0.515 0.95, 1 0.95, 1 0"></polygon></clipPath><clipPath id="clip-tablet-mobile-bottom-876b4912f7f93" class="decoration-clip clip-path-tablet-mobile-bottom" clipPathUnits="objectBoundingBox" data-screen="tablet-" decoration-type="pointer" pointer-width="7.000000000000001" pointer-height="3" style="" data-inverted="false"><polygon points="0 0, 0 0.97, 0.46499999999999997 0.97, 0.5 1, 0.5349999999999999 0.97, 1 0.97, 1 0"></polygon></clipPath></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-15de6af5c54"><div class="thrv_wrapper thrv-columns" style="" data-css="tve-u-15de6c5c622"><div class="tcb-flex-row tcb-resized tcb--cols--2" data-css="tve-u-15de67063f3"><div class="tcb-flex-col" data-css="tve-u-15de6706c4f" style=""><div class="tcb-col tve_empty_dropzone" style=""><div class="thrv_wrapper tve_image_caption" data-css="tve-u-15de66f9cfb" style=""><span class="tve_image_frame" style="width: 100%;"><img class="tve_image wp-image-2422" alt="" width="142" height="142" title="set_22_icon" data-id="2422" src="{tve_leads_base_url}/images/set_22_icon.png" style="width: 100%;"></span></div></div></div><div class="tcb-flex-col" data-css="tve-u-15de6706c53" style=""><div class="tcb-col tve_empty_dropzone" style=""><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-15de68e749e"><p data-css="tve-u-15df0d4308f">Subscribe to Our Newsletter!</p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-15de68e591c"><p data-css="tve-u-15df0d6290c">Aenean sollicitudin, lorem quis bibendum auctor, nisi elit ipsum, nec sagittis sem nibh id elit.</p></div></div></div></div></div></div>
</div><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" style="" data-css="tve-u-15de6aa041f">
<div class="tve-content-box-background" data-css="tve-u-15de6aab0fe"></div>
<div class="tve-cb tve_empty_dropzone"><div class="thrv_wrapper thrv_lead_generation" data-connection="api" style="" data-css="tve-u-15de6bae727"><input type="hidden" class="tve-lg-err-msg" value="{&quot;email&quot;:&quot;Email address invalid&quot;,&quot;phone&quot;:&quot;Phone number invalid&quot;,&quot;password&quot;:&quot;Password invalid&quot;,&quot;passwordmismatch&quot;:&quot;Password mismatch error&quot;,&quot;required&quot;:&quot;Required field missing&quot;}">
<div class="thrv_lead_generation_container tve_clearfix">
<form action="#" method="post" novalidate="novalidate">
<div class="tve_lead_generated_inputs_container tve_clearfix tve_empty_dropzone">
<div class="thrv_wrapper thrv-columns"><div class="tcb-flex-row tcb--cols--3"><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input" data-css="tve-u-15de6bb2fca">
<input type="text" data-field="name" name="name" placeholder="Your Name" data-placeholder="Your Name" style="" data-required="0" data-validation="" class="">
</div></div></div><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input" data-css="tve-u-15de6bb2fcb">
<input type="email" data-field="email" data-required="1" data-validation="email" name="email" placeholder="Your Email" data-placeholder="Your Email" style="" class="">
</div></div></div><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_submit_container tve_lg_submit" data-css="tve-u-15de6b9af8a">
<button type="submit" style="" class="tve-froala"><span class=""><strong>SUBSCRIBE</strong></span></button>
</div></div></div></div></div>
</div>
<input type="hidden" name="__tcb_lg_fc" id="__tcb_lg_fc" value="YTowOnt9"><input id="_submit_option" type="hidden" name="_submit_option" value="message"><input id="__tcb_lg_msg" type="hidden" name="__tcb_lg_msg" value="YToyOntzOjU6ImVycm9yIjtzOjY6IkVycm9yISI7czo3OiJzdWNjZXNzIjtzOjA6IiI7fQ=="></form>
</div>
</div></div>
</div></div>
</div>