<div class="thrv-leads-form-box tve_no_drag tve_no_icons thrv_wrapper tve_editor_main_content thrv-leads-in-content tve_empty_dropzone" style="" data-css="tve-u-159aeba1b19a69"><div class="thrv_wrapper thrv-columns" style="" data-css="tve-u-1159aeba1b19acb"><div class="tcb-flex-row tcb-resized tcb--cols--2" data-css="tve-u-1159aeba1b19b2e"><div class="tcb-flex-col" data-css="tve-u-1159aeba1b19b9e" style=""><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper tve_image_caption" data-css="tve-u-1159aeba1b19bfd" style=""><span class="tve_image_frame" style="width: 100%;"><img class="tve_image wp-image-2424" alt="" width="142" height="142" title="set_24_icon" data-id="2424" src="{tve_leads_base_url}/images/set_24_icon.png" style="width: 100%;"></span></div></div></div><div class="tcb-flex-col" data-css="tve-u-1159aeba1b19c59" style=""><div class="tcb-col tve_empty_dropzone" style="" data-css="tve-u-1159aeba1b19caf"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-1159aeba1b19d0e"><p data-css="tve-u-1159aeba1b19d6c" data-default="Enter your text here..."><strong>Subscribe to the Newsletter!</strong></p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style=""><p data-css="tve-u-1159aeba1b19dcc" data-default="Enter your text here...">Aenean sollicitudin, lorem quis bibendum auctor, nisi elit ipsum, nec sagittis sem nibh id elit.</p></div></div></div></div></div><div class="thrv_wrapper thrv_lead_generation" data-connection="api" style="" data-css="tve-u-1159aeba1b19e2b"><input type="hidden" class="tve-lg-err-msg" value="{&quot;email&quot;:&quot;Email address invalid&quot;,&quot;phone&quot;:&quot;Phone number invalid&quot;,&quot;password&quot;:&quot;Password invalid&quot;,&quot;passwordmismatch&quot;:&quot;Password mismatch error&quot;,&quot;required&quot;:&quot;Required field missing&quot;}">
<div class="thrv_lead_generation_container tve_clearfix">
<form action="#" method="post" novalidate="novalidate">
<div class="tve_lead_generated_inputs_container tve_clearfix tve_empty_dropzone">
<div class="thrv_wrapper thrv-columns"><div class="tcb-flex-row tcb--cols--3"><div class="tcb-flex-col" data-css="tve-u-1159aeba1b19e93"><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input tcb-icon-display tve_empty_dropzone" data-css="tve-u-1159aeba1b19ef1">
<input type="text" data-field="name" data-required="0" data-validation="" name="name" placeholder="Name" data-placeholder="Name" class="" style="">
</div></div></div><div class="tcb-flex-col" data-css="tve-u-1159aeba1b19f51" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input tcb-icon-display tve_empty_dropzone" data-css="tve-u-1159aeba1b19fb0">
<input type="email" data-field="email" data-required="1" data-validation="email" name="email" placeholder="Email" data-placeholder="Email" class="" style="">
</div></div></div><div class="tcb-flex-col" data-css="tve-u-1159aeba1b1a02b" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_submit_container tve_lg_submit" data-css="tve-u-1159aeba1b1a096">
<button type="submit" class="tve-froala" style="">SUBSCRIBE</button>
</div></div></div></div></div>
</div>
<input type="hidden" name="__tcb_lg_fc" id="__tcb_lg_fc" value="YTowOnt9"><input id="_submit_option" type="hidden" name="_submit_option" value="reload"><input id="_back_url" type="hidden" name="_back_url" value=""></form>
</div>
</div></div>