<div class="thrv-leads-form-box tve_no_drag tve_no_icons thrv_wrapper tve_editor_main_content thrv-leads-in-content tve_empty_dropzone" style="" data-css="tve-u-6159aeb9dd94053"><div class="thrv_wrapper thrv-page-section" style="" data-css="tve-u-6159aeb9dd940c1">
<div class="tve-page-section-out" data-css="tve-u-6159aeb9dd9411f" data-clip-id="09c8050c4cbcf"><svg width="0" height="0" class="tve-decoration-svg"><defs><clipPath id="clip-bottom-09c8050c4cbcf" class="decoration-clip clip-path-bottom" clipPathUnits="objectBoundingBox" data-screen="" decoration-type="pointer" pointer-width="5" pointer-height="9" style=""><polygon points="0 0, 0 0.91, 0.475 0.91, 0.5 1, 0.525 0.91, 1 0.91, 1 0"></polygon></clipPath><clipPath id="clip-mobile-bottom-09c8050c4cbcf" class="decoration-clip clip-path-mobile-bottom" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="pointer" pointer-width="5" pointer-height="2" style=""><polygon points="0 0, 0 0.98, 0.475 0.98, 0.5 1, 0.525 0.98, 1 0.98, 1 0"></polygon></clipPath></defs></svg></div>
<div class="tve-page-section-in tve_empty_dropzone"><div class="thrv_wrapper thrv-columns" style=""><div class="tcb-flex-row tcb-resized tcb--cols--2" data-css="tve-u-6159aeb9dd941a6"><div class="tcb-flex-col" data-css="tve-u-6159aeb9dd94201" style=""><div class="tcb-col tve_empty_dropzone" style=""><div class="thrv_wrapper tve_image_caption" data-css="tve-u-6159aeb9dd94260" style=""><span class="tve_image_frame" style="width: 100%;"><img class="tve_image wp-image-2422" alt="" width="142" height="142" title="set_22_icon" data-id="2422" src="{tve_leads_base_url}/images/set_22_icon.png" style="width: 100%;"></span></div></div></div><div class="tcb-flex-col" data-css="tve-u-6159aeb9dd942bb" style=""><div class="tcb-col tve_empty_dropzone" style="" data-css="tve-u-6159aeb9dd94304"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-6159aeb9dd94366"><p data-default="Enter your text here..." data-css="tve-u-6159aeb9dd943b3"><strong>Subscribe to our Newsletter!</strong></p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-6159aeb9dd94409"><p data-css="tve-u-6159aeb9dd9446c" data-default="Enter your text here...">Aenean sollicitudin, lorem quis bibendum auctor, nisi elit ipsum, nec sagittis sem nibh id elit.</p></div></div></div></div></div></div>
</div><div class="thrv_wrapper thrv-page-section" style="" data-css="tve-u-6159aeb9dd944cb">
<div class="tve-page-section-out"></div>
<div class="tve-page-section-in tve_empty_dropzone"><div class="thrv_wrapper thrv_lead_generation" data-connection="api" style="" data-css="tve-u-6159aeb9dd94536"><input type="hidden" class="tve-lg-err-msg" value="{&quot;email&quot;:&quot;Email address invalid&quot;,&quot;phone&quot;:&quot;Phone number invalid&quot;,&quot;password&quot;:&quot;Password invalid&quot;,&quot;passwordmismatch&quot;:&quot;Password mismatch error&quot;,&quot;required&quot;:&quot;Required field missing&quot;}">
<div class="thrv_lead_generation_container tve_clearfix">
<form action="#" method="post" novalidate="novalidate">
<div class="tve_lead_generated_inputs_container tve_clearfix tve_empty_dropzone">
<div class="thrv_wrapper thrv-columns"><div class="tcb-flex-row tcb--cols--3"><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input" data-css="tve-u-6159aeb9dd9458b">
<input type="text" data-field="name" name="name" placeholder="Name" data-placeholder="Name" style="">
</div></div></div><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input" data-css="tve-u-6159aeb9dd945da">
<input type="email" data-field="email" data-required="1" data-validation="email" name="email" placeholder="Email" data-placeholder="Email">
</div></div></div><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_submit_container tve_lg_submit" data-css="tve-u-6159aeb9dd94641">
<button type="submit" class="tve-froala" style="">SUBSCRIBE</button>
</div></div></div></div></div>
</div>
</form>
</div>
</div></div>
</div></div>